### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by saxenarohit** [alinlab/HOMER#2]
Hi,

Amazing work. I am working on something similar and would like to compare. Will it be possible to release the code? 

Thanks!

**Comment by woominsong** [comment]
Sorry for the delay. The refactoring process took longer than expected, and no members of our team are currently available to work on the code at this moment. However, we will shortly get back and release the code. Thank you for your patience.

**Comment by EagleW** [comment]
@woominsong Hi, thank you for your amazing work! Do you have an estimation of when the code will become available? Thank you again for your help!

**Comment by Mooler0410** [comment]
Impressive work. Curious about when will the codes been released. I believe the core codes are good enough for us folks. Looking forward to having a test!

**Comment by woominsong** [comment]
@EagleW @Mooler0410 Thanks a lot for your interest in our work! We have implemented an initial version of the refactored code and plan to undergo some validation tests before releasing it. We expect to release the code in about a week. Thanks again for your patience, and sorry for the delay.

**Comment by hgfriver681** [comment]
Amazing work! Can't wait for this masterpiece!

**Comment by Mooler0410** [comment]
> @EagleW @Mooler0410 Thanks a lot for your interest in our work! We have implemented an initial version of the refactored code and plan to undergo some validation tests before releasing it. We expect to release the code in about a week. Thanks again for your patience, and sorry for the delay.

Really appreciate it! Eagerly looking forward to it!

**Comment by woominsong** [comment]
The code is now released. Thank you for your patience, and please let me know if you have any questions!

**Comment by EagleW** [comment]
Thank you so much!

**Comment by Mooler0410** [comment]
Thanks!
